#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
	echo "warning: root needed, trying sudo..." 1>&2
	sudo -V > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "error: sudo not found" 1>&2
		echo "note: on Debian try run '$0' under root" 1>&2
		exit 2
	else
		echo "info: successfully copied"
	fi
	sudo $0
	exit 1
fi

cp bin/lib*.so /usr/lib
cp -r include/** /usr/include
